server:
  port: 9002

spring:
  application:
    name: convertcurrms

eureka:
  instance:
    instanceId: convertcurrms
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
    metadata-map:
      zone: ZoneA
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: true  
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  